### ISSUE TITLE
Make Google Demo Sheet Available As Template

### ISSUE THREAD

**Issue by sheadawson** [diegomanuel/binance-to-google-sheets#1]
Hey Diego, nice work on this, it's just what I'm looking for.

Any chance you can update the sharing permissions on the demo sheet so that we can use it as a base template? 

Currently I can't even copy/paste cells to pull your layout into my own sheet.

Many thanks :)

**Comment by diegomanuel** [comment]
Hey there! Sure thing, it's done. Try again and you should be able to download/copy the whole spreadsheet :smiley: 
Glad to hear you like it, thanks to you for your kind words, enjoy! :beers:

**Comment by sheadawson** [comment]
Legend! Thanks :D
