### ISSUE TITLE
[BUG] Function onOpen

### ISSUE THREAD

**Issue by Matts007** [diegomanuel/binance-to-google-sheets#106]
Hi,

I was trying to use Binance to google sheets, but it looks like and what I can understand Google change APIs and the way it authenticates.
Can you check and let me know if I'm doing something wrong?

Please see logs and screenshot below:
<html>
<body>

Head | onOpen | Simple Trigger | Oct 13, 2021, 10:03:14 PM | 8.845 s | Failed
-- | -- | -- | -- | -- | --
Cloud logsOct 13, 2021, 10:03:23 PMErrorException: You do not have permission to call ScriptApp.getProjectTriggers. Required permissions: https://www.googleapis.com/auth/script.scriptapp     at _configTriggers(Code:3173:15)     at init(Code:2885:5)     at onOpen(Code:2833:11)

</body>
</html>

![Error](https://user-images.githubusercontent.com/92482480/137213639-3222e091-8448-441e-bcb9-59aeb5993845.JPG)

PS

I don't know if that matters, but I'm trying to load Binance.com and my local zone is Ireland.

Thanks

Matt

**Comment by diegomanuel** [comment]
Hey @Matts007 it seems that Google changed some things behind curtains and it started to fail the `onOpen()` trigger with lack of permissions, although the right permission (`https://www.googleapis.com/auth/script.scriptapp`) is set at `appsscript.json`.

The only way I found to get it back to work, was to create the `onOpen` trigger myself from the Apps Script manager:
https://stackoverflow.com/questions/21219031/execution-failed-you-do-not-have-permission-to-call-getprojecttriggers
Something like:
![image](https://user-images.githubusercontent.com/5076158/142907402-77b5b626-b05c-4a5b-926c-de5e659698c0.png)
It asked me again to give permissions to the script, and after doing that it started to work again.

PS: I'm currently seeing 2 `onOpen()` executions when opening the spreadsheet, one failing with the permission issue (the original one) and the new manually-set that runs fine... but I can live with that.

Cheers! :beers:
