### ISSUE TITLE
[FEATURE] USD Margin Futures 

### ISSUE THREAD

**Issue by KlaSun** [diegomanuel/binance-to-google-sheets#11]
Have the same functionality as for Spot/Margin/Isolate but for Futures. Particularly "Positions" for Futures
Exactly the same as for Spot but call BINANCE("account", "futures") or something like that

Amazing product btw :)

**Comment by diegomanuel** [comment]
Hey @KlaSun thank you!
Of course it will be added in the very near future for `v0.4.1`, so stay tuned.  =]
Good luck, cheers! :beers:

**Comment by KlaSun** [comment]
Great ! Looking forward to it :)

**Comment by diegomanuel** [comment]
Done and released at **v0.5.0**!
https://github.com/diegomanuel/binance-to-google-sheets/releases/tag/v0.5.0
