### ISSUE TITLE
[BUG] Script loading... - error with permissions

### ISSUE THREAD

**Issue by CyborgXR8** [diegomanuel/binance-to-google-sheets#127]
Hi, I had installed previously the Binance API into my google sheet, and it worked perfectly.

My google account got compromised and I deleted all access permissions, including your Binance API.
I got back into the sheet and activated it, and got success messages, just like the first time, but it doesn't work anymore.

I uninstalled the project and did it all over again, even with new API keys... It doesn't work.
I copied the sheet and reinstalled the project again. It still doesn't work.

All I get is the loading error in the cell.
![Screenshot_1](https://user-images.githubusercontent.com/100850075/156572312-8e8c1b8a-8a7c-4fdb-aa5f-cea77fdbbecb.png)

I manually added a simple trigger on "onOpen", and allowed access again, but it still shows me this error in execution:

Exception: You do not have permission to call ScriptApp.getProjectTriggers. Required permissions: https://www.googleapis.com/auth/script.scriptapp
    at _configTriggers(BINANCE:2073:15)
    at init(BINANCE:1781:5)
    at onOpen(BINANCE:1729:11)

What can I do? Thank you!

**Comment by HavaneFr** [comment]
Same problem since 1 day, stuck to "loading data", but nothing in the execution log.

**Comment by CyborgXR8** [comment]
Issue resolved itself, it works today.
