### ISSUE TITLE
[BUG] Cells stuck on “Loading…“ for at least 2 days.

### ISSUE THREAD

**Issue by AMNKart** [diegomanuel/binance-to-google-sheets#128]
Hi there,

it's been at least 2 days some of the cells that contain a BINANCE() formula in my Spreadsheet are stuck on “Loading…“ state.

Usually, when this happens I clear the problematic cell and re-insert the formula and it works. But this time it doesn't.

The two main formulas I use are BINANCE("prices", ...) and BINANCE("history", …).
Here's a list of tickers that are concerned by the issue: AXS, LUNA ,DREP, GLMR, BNB, BICO.
The following tickers work just fine: ETH, BTC, ALGO.

I wonder if anyone else is experiencing the same issue...

Thanks in advance for the help!

**Comment by imfery** [comment]
I'm experiencing the same issue

**Comment by Astewart1510** [comment]
I am experiencing the same issue... has something changed from binances API?
