### ISSUE TITLE
[BUG] Auto refresh when chart has own sheet

### ISSUE THREAD

**Issue by FredSavage69420** [diegomanuel/binance-to-google-sheets#13]
**Describe the bug**
doRefresh(X)m Exception: Range not found (+various lines)

**To Reproduce**
1. Insert > chart
2. Click on three dots top right of chart > "move to own sheet"
3. See execution log errors (or Binance > Refresh: "The action is not supported for OBJECT sheet"

Functionality restored by deleting sheet with chart

**Comment by diegomanuel** [comment]
Hey @FredSavage69420 thank you very much for catching this up! :clap: 

I was able to reproduce and fix the issue.
It will be available **very soon** in the coming `v0.4.1` release.

Please re-open this issue if the new release doesn't resolve the problem.
Thanks again, cheers! :beers:

**Comment by FredSavage69420** [comment]
No problem!  Happy to have been of assistance 👍
