### ISSUE TITLE
[BUG] Enter a descriptive title here

### ISSUE THREAD

**Issue by Armaan1Gohil** [diegomanuel/binance-to-google-sheets#141]
**Describe the bug**
 When using =BINANCE("prices", "BETH"), the output is "?". The currency value of some other coins like ETHW are showing the same error.

**To Reproduce**
Go to cell and write: =BINANCE("prices","BETH")

**Expected behavior**
the value for BETH should have been displayer, instead "?" appeared.

**Comment by diegomanuel** [comment]
That's because the pair "BETHUSDT" doesn't exist. The default ticker is USDT if not given.
You should use, ie: ` =BINANCE("prices","BETH", "BUSD")`
