### ISSUE TITLE
I'm trying to use the PROXY. What should be the value of the USE_PROXY variable 

### ISSUE THREAD

**Issue by rugobal** [diegomanuel/binance-to-google-sheets#147]
I'm trying to use the proxy as described here:

https://github.com/diegomanuel/binance-to-google-sheets-proxy

What should be the value of the USE_PROXY variable? A public domain from an allowed country? Or my public IP if I'm in an an allowed country? I don't get that.

Thanks

**Comment by rugobal** [comment]
Ok, I already figured it out. Working now :)

**Comment by aarmed** [comment]
What was your solution?

**Comment by diegomanuel** [comment]
That should be the domain or the public IP in **where you setup the proxy server to run**!
IE: http://1.2.3.4  or https://somedomain.com
The http**s** (with SSL cert) is recommended but not mandatory.

**Comment by rugobal** [comment]
Yes, I got a domain from no-ip and unfortunately I had to get also a ssl cert because it didn't otherwise
