### ISSUE TITLE
[FEATURE] Proxy for Windows

### ISSUE THREAD

**Issue by The-Naken** [diegomanuel/binance-to-google-sheets#149]
How can i set up the proxy for Windows ?  I never done this before some help is welcome ! 

@diegomanuel  Thank you for the work you provided .

**Comment by aarmed** [comment]
Also interested, thanks.

**Comment by jeanmouawad** [comment]
Interested

**Comment by Hoochie63** [comment]
+1

**Comment by diegomanuel** [comment]
Install erlang+elixir for windows, or run a virtual machine, or an instance at AWS/GCP, etc.
Sorry folks, but I'm not a windows user, not going to write any specific instructions for it.
However you can google it to find plenty of resources on how to run erlang+elixir at any OS.

If someone wants to write down a how-to for windows, feel free to reopen this ticket.
