### ISSUE TITLE
[BUG] Enter a descriptive title here

### ISSUE THREAD

**Issue by F0liveira** [diegomanuel/binance-to-google-sheets#150]
**Describe the bug**
After installing the add-on correctly following the README, I had that issue trying to retrieve the price of BTC. It shows me #ERROR on the cell.

**To Reproduce**
1. Select a Cell and copy the folowing: =BINANCER("prices": "BTC")

**Expected behavior**
It should retrieve me the price of BTC on the cell. 

**Screenshots**
![image](https://user-images.githubusercontent.com/48527952/222888494-8a52ab33-00ce-42d7-b460-0029395de541.png)

**Additional context**
I went on the Script Editor and ran the script and it gave me the same issue at the same line. I also tried other commands but I've got the same issue too.

**Comment by diegomanuel** [comment]
The script is working fine, it seems you used `:` between `"prices"` and `"BTC"`.
The correct way is with `,` like: `=BINANCE("prices", "BTC")`
