### ISSUE TITLE
[BUG] Script shows error 451

### ISSUE THREAD

**Issue by odmivolsi** [diegomanuel/binance-to-google-sheets#151]
I have setup the script as mentioned in the tut. Even entered API keys. 
But on typing BINANCE("prices") I'm getting error after loading. The following error is shown:

> Error: Request failed with status: 451 (line 1876)

It shows the version correctly when i type BINANCE("version")
I'm not a coder so someone help me out here

**Comment by diegomanuel** [comment]
It's not an add-on bug, plz read this report: https://github.com/diegomanuel/binance-to-google-sheets/issues/142#issuecomment-1345361826
