### ISSUE TITLE
[BUG] Error occurred on fetching -> SyntaxError: Unexpected token '<', "<!doctype "... is not valid JSON (line 1688).

### ISSUE THREAD

**Issue by aldecode** [diegomanuel/binance-to-google-sheets#157]
**Describe the bug**
Error occurred on fetching -> SyntaxError: Unexpected token '<', "<!doctype "... is not valid JSON (line 1688).

**To Reproduce**
1. Just refresh and get this error

**Expected behavior**
Data is fetched

**Screenshots**
<img width="1365" alt="image" src="https://github.com/diegomanuel/binance-to-google-sheets/assets/45916288/f23cf39d-2636-4be6-a57c-242ad89e1145">

**Workaround**
Change SPOT_API_URL in Code.gs to "https://binance.com" and add this URL to the urlFetchWhitelist array

**Comment by cryptoflip0** [comment]
Looks like a bug on Binance's end

QUERY: https://data.binance.com/api/v3/klines?symbol=LTCUSDT&interval=1d&limit=1000
RESPONSE: 403

There's a  HTTP 302 redirect which means the page has been moved temporarily.

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html>
<head><title>302 Found</title></head>
<body>
<center><h1>302 Found</h1></center>
<hr/>Powered by Tengine<hr><center>tengine</center>
</body>
</html>

The redirect goes back to Binance home page: https://www.binance.com/en

**Comment by cryptoflip0** [comment]
Ah it looks like the URL needs to be:
https://api.binance.com/api/v3/klines?symbol=LTCUSDT&interval=1d&limit=1000

...and not
https://data.binance.com/api/v3/klines?symbol=LTCUSDT&interval=1d&limit=1000


This returns HTTP 451
The HyperText Transfer Protocol (HTTP) 451 Unavailable For Legal Reasons client error response code indicates that the user requested a resource that is not available due to legal reasons, such as a web page for which a legal action has been issued.

**Comment by luckylacazz** [comment]
looks like the "problem" with the google ip restrictions...may be the proxy work-around will help

**Comment by luckylacazz** [comment]
if u want a solution just for the ticker, the solution for me was to switch the "spot_api_url"
![image](https://github.com/diegomanuel/binance-to-google-sheets/assets/146781972/d981548e-ab85-4f25-b8d8-7fcbe700ccec)

**Comment by aldecode** [comment]
Updated: if i change SPOT_API_URR to api.binance.us, and add us urls to the white list, it starts randomly show some of the columns, but others have like "Exception: DNS error: https://api2.binance.us/api/v3/ticker/24hr? (строка 1681)." error, same for api1 and api3 btw, so my guess is just "API" in URL works fine. I am not sure now how requests are distributed between this 4 APIs

**Comment by aldecode** [comment]
Actually, when I tried to use binance.com instead of binance.us, I got the problem described [here](https://github.com/diegomanuel/binance-to-google-sheets/issues/142), that still not resolved. Workarounds not working anymore

**Comment by Hoochie63** [comment]
> Updated: if i change SPOT_API_URR to api.binance.us, and add us urls to the white list, it starts randomly show some of the columns, but others have like "Exception: DNS error: https://api2.binance.us/api/v3/ticker/24hr? (строка 1681)." error, same for api1 and api3 btw, so my guess is just "API" in URL works fine. I am not sure now how requests are distributed between this 4 APIs

Add all APIs to the whitelist that give an error, like this:
![image](https://github.com/diegomanuel/binance-to-google-sheets/assets/23609223/14e3ad8e-2c3e-444b-b395-d914174b3e33)

**Comment by aldecode** [comment]
> > Updated: if i change SPOT_API_URR to api.binance.us, and add us urls to the white list, it starts randomly show some of the columns, but others have like "Exception: DNS error: https://api2.binance.us/api/v3/ticker/24hr? (строка 1681)." error, same for api1 and api3 btw, so my guess is just "API" in URL works fine. I am not sure now how requests are distributed between this 4 APIs
> 
> Add all APIs to the whitelist that give an error, like this: ![image](https://user-images.githubusercontent.com/23609223/272310318-14e3ad8e-2c3e-444b-b395-d914174b3e33.png)

I did it, but this hasn`t helped me

**Comment by aldecode** [comment]
Actually, I managed to get some data removing distribution between api1-api3 in the makeApiUrl method(function =)), just using the regular one, but prices seem outdated and not relevant on binance.us, so this is still not a workaround. Moreover, I think there was some reason to distribute calls

![image](https://github.com/diegomanuel/binance-to-google-sheets/assets/45916288/f3183b7b-612d-42c1-9a6a-6223eeb386a7)

**Comment by Hoochie63** [comment]
> Seems there is a simple workaround:
> 
> Just change SPOT_API_URL to "https://binance.com" and add "https://binance.com/" to appsscript.json. Not sure it will work for a long time but it is what it is :)
> 
> P.S. Unfortunately it will not work for the USD ticker if you used it as I

Interesting solution :)
I take into account the USDT rate, so there are no problems with displaying all rates. Thanks for the advice!

**Comment by 0ri0nRo** [comment]
I had the same problem, but I haven't resolve it yet
