### ISSUE TITLE
[BUG] Error when trying to get orders table

### ISSUE THREAD

**Issue by FellipeBr** [diegomanuel/binance-to-google-sheets#18]
**Describe the bug**
When I try to use the command to download the orders table, it gives me the error:

 `ERROR: A range with crypto symbols must be given!	`

But i'm actually pointing to the symbols that I have on my SPOT account:

`=BINANCE("orders/table"; SPOT!A4:A11; "BUSD")`

![image](https://user-images.githubusercontent.com/3584098/109352502-b2ac7080-7859-11eb-90a8-c872bb28b2e2.png)

![image](https://user-images.githubusercontent.com/3584098/109352550-c6f06d80-7859-11eb-80c8-35201e736b12.png)

**Comment by diegomanuel** [comment]
Hey @FellipeBr thanks for reporting the issue.

That error happened on release `v0.4.1` (the current one) right?
If that's the case, it should be already solved on `master` but the fix will be included at `v0.4.2` release in a few more days.
If you've already tried the latest code from `master` and it's still happening, please let me know by re-opening this issue!

Stay tuned, thanks again! :beers:

**Comment by diegomanuel** [comment]
Just in case, try with "," (comma) instead of ";" at:
`=BINANCE("orders/table", SPOT!A4:A11, "BUSD")`

Google Spreadsheet should automatically change the ";" to "," but maybe not in your case (?)
I think that using ";" could cause problems.
Good luck!
