### ISSUE TITLE
[BUG] orders table error

### ISSUE THREAD

**Issue by ziggetty** [diegomanuel/binance-to-google-sheets#19]
got the following in the log

Feb 26, 2021, 9:59:40 PM
Info
[BinDoOrdersTable] Saving 4 downloaded records into 'Orders Table' sheet..
Feb 26, 2021, 9:59:41 PM
Error
{ [Exception: The coordinates of the range are outside the dimensions of the sheet.] name: 'Exception' }
Feb 26, 2021, 9:59:41 PM
Info
[BinDoOrdersTable] Done!

see the 4 orders in the table.

**Comment by diegomanuel** [comment]
Hey @ziggetty thanks for reporting the issue.
It's already solved on `master` but the fix it will be included at `v0.4.2` release in a few more days.
Stay tuned, thanks again! :beers:
