### ISSUE TITLE
[FEATURE] get historical data

### ISSUE THREAD

**Issue by georgio-sd** [diegomanuel/binance-to-google-sheets#2]
Hi,
Is there a way to get historical data?
For example bitcoin price on some date.

**Comment by diegomanuel** [comment]
Hello there Georgio, I think it can be done with this API endpoint:
https://github.com/binance/binance-spot-api-docs/blob/master/rest-api.md#klinecandlestick-data

I could add a new operation to get that information, but what's your usage idea?
Feel free to share your thoughts!

**Comment by diegomanuel** [comment]
Hello there @georgio-sd, I think it can be done with this API endpoint:
https://github.com/binance/binance-spot-api-docs/blob/master/rest-api.md#klinecandlestick-data

I could add a new operation to get that information, but what's your usage idea?
Feel free to share your thoughts, thanks!
