### ISSUE TITLE
[FEATURE] Create LIMIT ORDERS it will be possible?? 

### ISSUE THREAD

**Issue by DaLlrium** [diegomanuel/binance-to-google-sheets#23]
Hi Diego, we have developed a small project using some of your tools ... Thanks for this. We would like to know if it would be possible to generate limit orders from our google sheets ... Thanks.

**Comment by diegomanuel** [comment]
Hey @DaLlrium glad to hear that, good luck and remember to share it to the world! :clap: 

Yep it's totally possible to make the spreadsheet to create orders of any kind in any market (spot, cross, futures..).
You just need to call the right endpoints and of course use an API key that has permissions to create orders.

Stay tuned for fixes/upgrades here that might be useful to your project.
Happy trading, cheers! :beers:
