### ISSUE TITLE
Wrong data for some tokens

### ISSUE THREAD

**Issue by dskarasev** [diegomanuel/binance-to-google-sheets#26]
Hi there,

I just found that some tokens get wrong price data. For example token CRV (Curve DAO Token) shows price $34,251 per 1 CRV, But on Binance it's price just $2,33
The same for Cover protocol token COVER, your script display $2,34 then on coincecko it's $513,75
Please check why it's happening. Thanks!

**Comment by diegomanuel** [comment]
Hey @dskarasev that's weird, the add-on just returns and display the data as it gets it from Binance API.
It's even weirder that **some** prices are wrong, so I assume that was a temporary error from Binance and they should already have resolved it.

If the problem persist, please let me know by re-opening this issue and sharing the specific pairs having issues.
Good luck, cheers! :beers:

**Comment by dskarasev** [comment]
Hi, Diego!

The error didn't go away. The command " =BINANCE ("account"; "";) "shows the balances correctly, but the code from the dashboard example" =BINANCE ("prices"; A10:A; " ticker: "&B8&", prices: true")" does not recognize the correct price of most tokens. For example for the following tokens the price is not displayed at all:
MFT
PHA
PROM
RSR
RVN
TRB
USDT
XEM

For other tokens, for example, the FXS price is displayed incorrectly.
I think the problem is that the names of tokens are used instead of unique identifiers.

**Comment by diegomanuel** [comment]
Fixed at #29! :tada:
