### ISSUE TITLE
[BUG] Enter a descriptive title here

### ISSUE THREAD

**Issue by PaulAntonDeen** [diegomanuel/binance-to-google-sheets#28]
**Describe the bug**
![image](https://user-images.githubusercontent.com/25848961/110948918-3c703980-8342-11eb-8b56-dafa15429ae9.png)

**To Reproduce**
Enter =BINANCE("prices", "BNB", "BTC") in a cell
also tried =BINANCE("prices", A17:A, "ticker: "&B17&", prices: true")

**Expected behavior**
Price of crypto's

**Screenshots**

**Additional context**

**Comment by PaulAntonDeen** [comment]
Not sure what it was but on retry in another sheet I could get it to work

**Comment by diegomanuel** [comment]
Hey @PaulAntonDeen glad to hear it was just a weird behaviour.
The code should work for simple cases like the one you described, never had an issue with that operation.

You may need to ensure the code you copy/pasted is right.
If needed, copy the whole contents from the latest release and paste it again:
https://github.com/diegomanuel/binance-to-google-sheets/releases/download/v0.4.1/BINANCE.gs
NOTE: There are some fixes/improves at master branch that weren't released yet.

Thanks, good luck! :beers:
