### ISSUE TITLE
[FEATURE] Force refresh binding to a field

### ISSUE THREAD

**Issue by fellipute** [diegomanuel/binance-to-google-sheets#30]
**Describe the solution you'd like**
A way for us to bind the formula to a specific field (let's say a checkbox), so when the field changes it forces an update;

**Additional context**
I"ve seen some other tools doing that, so if we want to force the refresh instead of waiting for the refresh rate, we would just click on the field with the checkbox and that would trigger the update of all formulas.

**Comment by ziggetty** [comment]
you can do that

example i used =BINANCE("orders/open",,"headers:false",Account!R1&$A$1)

you can even combine several checkboxes as i have done in this example,
checkbox in $A$1 and R1 in another tab

i have all the triggers in the state OFF, and do refreshes manual by checkboxes.

![afbeelding](https://user-images.githubusercontent.com/79652361/111366060-563bb480-8693-11eb-8dff-30bb3c8b2e9b.png)

**Comment by fellipute** [comment]
LOL i'm completely bind, didn't see that.
Thanks!

**Comment by diegomanuel** [comment]
Thanks @ziggetty for the right answer! :tada:
