### ISSUE TITLE
relative USDT price at specific time in history

### ISSUE THREAD

**Issue by ROBKAM75** [diegomanuel/binance-to-google-sheets#32]
Hi, first of all thanks for the work you have done.

I am interested in it related to paying taxes.

what I would like to pull of Binance is the following:

1-let´s say you buy a coin A with BTC, what was the price of BTC in USDT at the time of the buy.
2 you sell coin A for BTC, what is the price of BTC at the moment you sell your coin A.

why? 
to pay taxes here in spain (and imagene in more places) they want to you to convert to fiat to know your gains.

practical example:
at moment of buying coin A BTC is at 50.000 usdt.
you sell coin A at +10% gain (in BTC) and price of BTC is 30.000 usdt.
although you have now more BTC (+10%) you really lost a lot in usdt so you would not pay taxes (negative in balance)

or the other way around:
at moment of buying coin A BTC is at 50.000 usdt.
you sell coin A at -10% gain (in BTC) and price of BTC is 80.000 usdt.
although the sale of coin A gives you less BTC than you had originally your BTC to usdt value has risen. and you would 
have to pay tax over the difference in usdt.

is this possible to do in the google sheet?

kindest regards,

Rob
robkammerer75@gmail.com

**Comment by ziggetty** [comment]
i think it could be realized. with the new history function.
from your "orders table" you have a date/time field.
with this i think it could be done.

ofcourse tax rules are different in countries around the world

**Comment by ROBKAM75** [comment]
good Morning Diego,

thank you for getting back to me on this, (I am rather new with all of this)
Yes, I was able to get the history data directly from Binance, for some
reason it does not work
automatically in sheets.   =BINANCE("orders/table"; Hoja10!A1:A3) here I
only get the firt 3 lines but no data.

And yes there is a time stamp there that I want to use to get the
historical price from BTC.
How would you write the formula?

2021-01-25 1:41:29 BRDBTC BUY 259 144 37.296 144 BRD
=BINANCE("history", "BTCUSDT", " 2021-01-31 19:47:45  ")

this gives an error.

muchas gracias!

un saludo,


Rob Kammerer
whatsapp: +34 679456480
skype: rkammerer

**Comment by diegomanuel** [comment]
Hey @ROBKAM75 I'll try to help a little bit.

In your example: `=BINANCE("history", "BTCUSDT", " 2021-01-31 19:47:45  ")`
It should be, for example: `=BINANCE("history", "BTCUSDT", "interval: 1d, start: 2020-01-01, end: 2021-01-01")`
And you will have daily prices for the whole 2020.

Anyways, the feature requested here #31 (daily account snapshot) could help in this matter.
NOTE: Binance already have the "daily snapshot" available on their website/platform.

An alternative is to take into account just the trades done in the desired datetime range and summarize them. To get the total balance in USDT you just need to multiply each asset amount by its price at the last trade's date.
Iit's easy using the built-in spreadsheet's functions and the data made available by the add-on.

Good luck and stay tuned for future releases! :beers:

**Comment by ROBKAM75** [comment]
Thank you very much Diego!

will give it another try

kindest regards,

Rob Kammerer
whatsapp: +34 679456480
skype: rkammerer
