### ISSUE TITLE
[BUG] Incorrect column order for historical market values

### ISSUE THREAD

**Issue by JaviZurdo** [diegomanuel/binance-to-google-sheets#34]
The returned columns from function parse(...) in module tasks/do-historical-data.gs are in the wrong order

If the headers are 
const header = ["Open Time", "Open", "High", "Low", "Close", "Close Time", "Volume", "Trades"];

Then the items in the row should change from 
        new Date(parseInt(d[5])),
        parseFloat(d[6]),
to
        new Date(parseInt(d[6])),
        parseFloat(d[5]),

or change the order of the headers....

**Comment by diegomanuel** [comment]
Hey @JaviZurdo thanks for the report!

You'r right and the fix was pushed to `master` branch, it'll be available in the next release.
Thanks again, cheers! :beers:
