### ISSUE TITLE
[BUG] A range with crypto symbols must be given

### ISSUE THREAD

**Issue by Lefey** [diegomanuel/binance-to-google-sheets#38]
Hi Diego! Very nice project!
I have a problem with orders/table, always got error: **A range with crypto symbols must be given!**
What i am doing: 
In A1 cell of new sheet insert =BINANCE("orders/table"; "BTCUSDT"; "ticker: range")
If i try to use comma instead semicolon, got syntaxerror on sheet.
Also tried =BINANCE("orders/table"; "BTC"), not help.

Log from doTablesPoll function:
_Info	DONE loading data from API! Storing at cache..
Info	[BinWallet] Updating wallet assets for: SPOT
Info	[BinDoAccountInfo][SPOT] Done!
Info	[BinDoOrdersTable] Processing sheet: OrdersHistory
Error [Error: A range with crypto symbols must be given!]
Info	[BinDoOrdersTable] Done!_

**Comment by diegomanuel** [comment]
Hey @Lefey did you tried using `,` instead of `;`?
Something like: `=BINANCE("orders/table", "BTCUSDT", "ticker: range")`
That should work, good luck! :beers:

**Comment by Lefey** [comment]
>did you tried using `,` instead of `;`?
Hi!, yes, of course tried, but when i use `,` google sheet show syntaxerror.

**Comment by diegomanuel** [comment]
Hey @Lefey sorry but I have no idea of what could be happening there!
This should/must work: `=BINANCE("orders/table", "BTCUSDT", "ticker: range")`
No one reported the error you are having!

* From "Binance" main menu, disable cross, isolated and futures wallets (just spot will be enabled) and see what happens.
* Re-install the latest released code, make sure to clean any previous code in your Apps Script screen for your spreadsheet before pasting the add-on code in there.
* Try in a new blank spreadsheet, install the latest release again from scratch, configure new API keys.

Sorry to hear that, hope you can find the way! :crossed_fingers:

**Comment by Lefey** [comment]
@diegomanuel thanks for reply! And yes, i found the way! Problem was in google sheet locale settings, set it to US, and problem solved 👍
https://support.google.com/docs/thread/4271054?hl=en
