### ISSUE TITLE
[BUG] Google Sheets gives error "ReferenceError: BinUtils is not defined BINANCE	@ Untitled.gs:19 "

### ISSUE THREAD

**Issue by MorningPants** [diegomanuel/binance-to-google-sheets#4]
**Describe the bug**
I am unable to get the code fuctioning on sheets.  This error message appears:

![Error](https://user-images.githubusercontent.com/77476821/104684075-11080000-56ad-11eb-9c78-a57e5c105541.PNG)

I am probably missing some simple step to get this to install properly?  This code comes highly recommended, and I would like to use it even if my computer skills are lacking.

Thank you very much for your time.

**Comment by diegomanuel** [comment]
Hey, hello there! :wave:

It seems to be something wrong at your code editor, I can see 2 files very similar there: `Code.gs` and `code.gs`.
My advice would be to remove/delete one of them and keep just one, and pasting in there the latest release code from here:
https://github.com/diegomanuel/binance-to-google-sheets/releases/latest/download/BINANCE.gs
Once done, just save, close the editor and refresh (F5) your spreadsheet!

Let me know if you have any further problems (just reopen this issue).
Thank you, good luck and happy trading! :beers:

**Comment by MorningPants** [comment]
Thank you for your response and help!  I had a different crypto code in the other file, but deleting it made no difference.  It did make it past BinUtils this time, but got stuck at line 56 with this error message:	
Error: Unsupported operation given: 'undefined'
BINANCE	@ Code.gs:56

**Comment by diegomanuel** [comment]
Glad to hear that! The problem was surely the "Run" button since the script is not designed to be run from there.
You only need to copy/paste the code, save, and refresh the spreadsheet.

Enjoy, cheers! :beers:

**Comment by ZeroV0LT** [comment]
This same error happens to me too and as a complete nob I lost almost half a hour to understand why.

This happens when you import the wrong BINANCE.gs file.
There is the all in one file (the one linked in README) and the wrong one (you can download form src).
Maybe is better to rename the all in one file in something else to avoid this problem.

**Comment by diegomanuel** [comment]
Hey @ZeroV0LT good suggestion, thanks!
I've done the rename to avoid further mistakes.
Cheers :beers:
