### ISSUE TITLE
Error : Unsupported operation given

### ISSUE THREAD

**Issue by papanara** [diegomanuel/binance-to-google-sheets#40]
Execution Log

9:20:44 AM	Notice	Execution started
9:20:45 AM	Error	
Error: Unsupported operation given: 'undefined'
BINANCE	@ Binance.gs:56

**Comment by diegomanuel** [comment]
It seems you didn't copied the source code right.
Try copy/pasting again the contents of: https://github.com/diegomanuel/binance-to-google-sheets/releases/latest/download/BINANCE.gs
Make sure to don't have any previous contents (code) in any file in your Google Developer Console screen.
Good luck! :beers:
