### ISSUE TITLE
[BUG] new trades not received in tables/poll

### ISSUE THREAD

**Issue by ziggetty** [diegomanuel/binance-to-google-sheets#46]
i have  new trades, but am not receiving them in tables/poll

probably in an earlier run something went not OK ??, and now 
i get the following message:

[BinDoOrdersTable][SPOT] Skipping unchanged asset: AUDIOUSDT

should not be skipped.

after i commented out this test in the script (cq workaround)
i finally received the new trades.

probably in an earlier run of tables/poll the account info was kept,
but receiving the trades went wrong.
in next run account info was not changed and asset skipped.

in principle this test is also flawed, because i could buy & sell an asset
between 2 tables/poll runs. and that can result in no change in acct info
but with new trades.

**Comment by diegomanuel** [comment]
Hey @ziggetty I'm aware of the flaw you mention and so far I didn't find a better way of trying to optimize the amount of requests and runtime required to fetch all the assets without reaching a `418` dead-end or an operation timeout from Google's platform.
I will probably do something about this in the near future, but in the meantime I introduced the option parameter `unchanged: false` to skip the unchanged check (so you don't need to comment out the script code by hand).
The latest release should correctly handle errors on specific assets and they should be tried again in the next run, but the flaw about buy/sell (with the exact same final balance) between polls is still there, although very unlikely (low probability, always changes a few cents at least).

If your assets range is not too big (less than 10) you may keep the `unchanged: false` option for good.
Just check the logs to see if the whole `doTablesPoll` finishes well a few times.

Good luck, thanks!
