### ISSUE TITLE
[BUG] BINANCE("account") not working

### ISSUE THREAD

**Issue by cristipurdel** [diegomanuel/binance-to-google-sheets#47]
**Describe the bug**
=BINANCE("account") not working
I am getting the following:
Error
Error: Got 401 from Binance API! The keys aren't set or they are not valid anymore. (line 2843).

**To Reproduce**
=BINANCE("account")

**Expected behavior**
-

**Screenshots**
-

**Additional context**
=BINANCE("account", "spot") is working however

**Comment by cristipurdel** [comment]
Sorry, needed some time to work.
Great plugin :)

**Comment by cristipurdel** [comment]
reopened since =BINANCE("account", "spot") is working but not =BINANCE("account")

**Comment by Stomper113** [comment]
I have different issue. Account is working, but "account" "futures" isnt working 

Says error parsing formula.

**Comment by diegomanuel** [comment]
Please be aware that it will fail if your Binance API key has NOT enabled futures!

**Comment by cnw97** [comment]
I'm also getting this error. I have deleted and re-added the API along with enabling 'Futures' on Binanace.
