### ISSUE TITLE
[FEATURE] Get subaccount balance

### ISSUE THREAD

**Issue by gusleig** [diegomanuel/binance-to-google-sheets#5]
Binance has the subaccount feature and the API has support to get the balance.

To get the subaccount feature in Binance you just need to send an email to support and they quickly add this to your account.

It would be great if your script could add this feature, at least get the balance of a subaccount passing the email as a parameter.

Thank you for this great code.

**Comment by diegomanuel** [comment]
Hello! That could be a nice feature to have, let me take a further look and it could be available soon  :wink:

**Comment by diegomanuel** [comment]
Hey @gusleig the support for sub-accounts is ready and almost there! :rocket: 
It will be included in the next coming release (`v0.4.1`) very soon.
You will need to add the email for each sub-account from `Binance->Sub-Accounts` main menu.

**NOTE:** It will only allow you to add emails that are assigned to sub-accounts of your main Binance account (aka: the account from where the configured API keys belong).
**TIP:** If you want to have orders and other stuff from a sub-account, just create API keys for it from Binance site and create a new spreadsheet exclusive for this sub-account and configure the API keys there in the add-on.
If you also want to have an "all-in-one" spreadsheet, you could use `IMPORTRANGE` function to have data imported from different spreadsheets (and use `QUERY` function to merge&sort the imported ranges).

Stay tuned, cheers! :beers:
