### ISSUE TITLE
[BUG] maximum execution time exceeded

### ISSUE THREAD

**Issue by ziggetty** [diegomanuel/binance-to-google-sheets#52]
a weird error i have is the maximum execution time exceeded, which sometimes pops up
and i do not know why .... trigger in the OFF state and checkbox to renew not  changed.

![afbeelding](https://user-images.githubusercontent.com/79652361/114618914-37d4d300-9caa-11eb-8c33-611d6ada09ec.png)
so i had my account info and then suddenly this error pops up
i think it is a bug somewhere, but for now i then just do a renew after the error.
and it not only happens with the account info call. 
maybe it is not in the script, but some interaction between 'google sheet' and ???

**Comment by diegomanuel** [comment]
This could happen from time to time due to Google servers being laggy or when a single operation takes longer than the Google platform allows. Max cap is 5 minutes for background time-triggers (like `doTablesPoll`) and 1 minute for operations triggered from `=BINANCE()` formulas on the sheet.
If the problem persist, try to break down operations into smaller ones.

**Comment by ziggetty** [comment]
> 
> 
> This could happen from time to time due to Google servers being laggy or when a single operation takes longer than the Google platform allows. Max cap is 5 minutes for background time-triggers (like `doTablesPoll`) and 1 minute for operations triggered from `=BINANCE()` formulas on the sheet.
> If the problem persist, try to break down operations into smaller ones.

mostly that happens on my  =BINANCER("account",,"headers:false",$A$1)
but the account trigger is in the state off
so the data which is in that tab should be static

i have the sheet open and the tab has info and then suddenly
it is lost and
the time exceeded error is shown.

my gut feeling is that it is a quirk at google and not from the script
