### ISSUE TITLE
[FEATURE] Add parameters to exclude the base coin (ie. USDT)

### ISSUE THREAD

**Issue by afanjul** [diegomanuel/binance-to-google-sheets#55]
**Problem**
Whenever you want to list your assets to get the prices and the funds you have in it, the binance api always returns the USDT, BUSD, etc. as part of your assets, but as there is no pair with that (USDT/USDT) the price requests, order queries, etc. always return ? and the "excel breaks".

**Describe the solution you'd like**
My first solution approach would be to be able to choose to exclude the the "fiat" currency for any request returning my assets (like in account request). So we could execute BINANCE("account", "cross", {exclude:"USDT, BSUD"}). Now to be able to just output the "fiat" assets (and use in our excel without price pair, orders, etc.) (to complete your total assets balance, etc.) we should also have the opposite "include": BINANCE("account", "cross", {include:"USDT, BSUD"}).

**Describe alternatives you've considered**
Another alternative would be to consider the price of "fiat" currencies as "1". So wherever that we request the prices for a list including USDT, we overwrite the pair price for USDT/USDT to 1. But it's a worst solution I think.

**Additional context**
The context is just simple, I would like to have an "**automatic**" spreadsheet where I can see all my assets (not adding them manually) with all the data (actual price, holdings, balances) and without "**?**" in any cells do to the absence of USDT/USDT pairs...

**Comment by ziggetty** [comment]
would be nice, but i worked around it.
and build an iferror to return not found
=iferror(vlookup(I29&"*",'Orders - closed'!D$1:Q,14, FALSE),"not found")
![afbeelding](https://user-images.githubusercontent.com/79652361/115304317-1ae64700-a165-11eb-9e1e-daecc215af26.png)



further i did set up helper columns.
as binance in many cases just return the pair
![afbeelding](https://user-images.githubusercontent.com/79652361/115301930-2421e480-a162-11eb-8447-d3aeaed5df79.png)
above is my account info in column A-G
after H are my own columns
as in A18 is LDADA i have to strip the LD (LDADA is the symbol for ADA on interest)
so column I became my helper column , so in I18 is
"=if(left(A18,2)="LD",RIGHT(A18,LEN(A18)-2),A18)"  giving ADA in I18

in J18 i do a lookup in my closed orders to get my avg buy price
=iferror(vlookup(I18&"*",'Orders - closed'!D$1:Q,14, FALSE),"not found")

in my 'orders - closed' tab i calculate in helper columns my avg buy price
it is still a work in progress, now and then i find errors and try to correct them.

in column K i do a lookup for current price based against USDT
=IFERROR(IFS(I18=" "," ",I18="BUSD",1,I18="USDT",1,I18>" ",VALUE(INDEX('Prices - All'!A$3:B, MATCH(I18&"USDT",'Prices - All'!A$3:A,0), 2))),"")

prices-all tab contains all current prices
![afbeelding](https://user-images.githubusercontent.com/79652361/115303319-c4c4d400-a163-11eb-982d-f31206710df4.png)

i also created a seperate prices-usdt tab with a query to filter only the USDT pairs
=query('Prices - All'!$A$3:$B,"select A, B where A CONTAINS 'USDT' and NOT A CONTAINS 'BULLUSDT' and NOT A CONTAINS 'BEARUSDT' and NOT A CONTAINS 'UPUSDT' and NOT A CONTAINS 'DOWNUSDT' and NOT A STARTS WITH 'USD'")

stripped USDT of as follows
=left(A4,(len(A4)-4))

![afbeelding](https://user-images.githubusercontent.com/79652361/115304693-87614600-a165-11eb-8140-819ac3f58135.png)
