### ISSUE TITLE
[ERROR 403] Error al actualizar precios

### ISSUE THREAD

**Issue by fer2734** [diegomanuel/binance-to-google-sheets#56]
**Describe the bug**
En la planilla aparece el error 403 cada tanto y no me deja operar.

Habra alguna forma de evitar el baneo por parte de BINANCE?

Muchas gracias por el código, excelente aporte. Saludos desde Buenos Aires

**Comment by Roland-dB** [comment]
I get the same 403 error quite often. Sorry I don't speak Spanish, but I wanted to say this has been a recurring issue for some time.

**Comment by fer2734** [comment]
ok, I thought you were from Argentina, that's why I wrote in Spanish. In the end I had to stop using the code, and replaced it with IMPORTXML based on CoinMarketCap.

**Comment by Art3mS1d** [comment]
Same, not working from yesterday

**Comment by Art3mS1d** [comment]
Also, it's imposible to change update intervals from the menu

**Comment by diegomanuel** [comment]
The `403`s are due to heavy Binance API request from Google servers, seems that this code is being used too much :sweat_smile:
