### ISSUE TITLE
[FEATURE] Staking data

### ISSUE THREAD

**Issue by cristipurdel** [diegomanuel/binance-to-google-sheets#59]
**Is your feature request related to a problem? Please describe.**
Would be helpful to get info from https://www.binance.com/en/my/wallet/account/saving from Earn/Locked Staking/Locked

**Describe the solution you'd like**
Table format with all the associated headers

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by ziggetty** [comment]
related to #42

**Comment by diegomanuel** [comment]
Duplicated, will be done at #36!
