### ISSUE TITLE
[BUG] Orders Table show no result polling

### ISSUE THREAD

**Issue by nickpb** [diegomanuel/binance-to-google-sheets#62]
**Describe the bug**
Trying to pull the data from Order Table for 4 times and not succeed.

**To Reproduce**
1. Go to 'Orders Tale' tab
2. use "=BINANCE("orders/table", Dashboard!$A10:$A)" with your GS template on "A1"
4. See no result show up (see attached image for reference.)

**Expected behavior**
to polling 1,000 items(orders/table) every 10mins

[https://drive.google.com/file/d/11ETZ2Rd3b6XISMJ91jRysOftNfJMATr2/view?usp=sharing](url)

**Screenshots**
please refer to the screenshot

**Comment by diegomanuel** [comment]
Hey @nickpb if it's still failing, attach the logs from the Google Apps platform:
https://script.google.com/u/0/home/executions

But should work, although you can get many 418/403 responses.
