### ISSUE TITLE
Error unsupported operation given, 'undefined' (line 56, file 'code')

### ISSUE THREAD

**Issue by kerner99** [diegomanuel/binance-to-google-sheets#63]
I tried to follow your guide to install this into a speadsheet but this error is coming up. sorry i don't have any more detail, i am a complete noob just trying to keep track of my binance trades

**Comment by kerner99** [comment]
the bug appears after I have installed and added my API keys, after i have entered =binance(). in the same cell that I entered =binance(), the error appears. 
the error appears as, Error
Error: Unsupported operation given: 'undefined' (line 56).
 
I expected my binance data to appear in a spreadsheet. 

![Picture3](https://user-images.githubusercontent.com/83072493/115961002-605f9700-a50c-11eb-9048-902062738984.png)

**Comment by diegomanuel** [comment]
Hey @kerner99 you just need to give an operation there!

I recommend you to read: https://github.com/diegomanuel/binance-to-google-sheets#ok-i-have-it-installed-how-do-i-use-it-at-my-spreadsheet
You can also take a look to the live demo spreadsheet here:
https://docs.google.com/spreadsheets/d/1AcOcPFsncrDB_ve3wWMHwfiFql6A4hmG1sFc01LLTDg/edit#gid=1522299933

Good luck!
