### ISSUE TITLE
[BUG] =BINANCER

### ISSUE THREAD

**Issue by federico-galli** [diegomanuel/binance-to-google-sheets#64]
Hi, first of all thanks for your work.
I have noticed that sometimes the instruction

=BINANCE("account";"spot")

change... by herself into

=BINANCER("account";"spot")

I have seen the same on your DEMO

![image](https://user-images.githubusercontent.com/921088/116064449-519cef80-a686-11eb-9967-f50806cf00ea.png)
Why is that?

**Comment by rilax1010** [comment]
It's not a bug, it's for the refreshing. Explained in the comments of [](https://github.com/diegomanuel/binance-to-google-sheets/blob/master/main.gs)

**Comment by federico-galli** [comment]
Oh! I see! Thanks again

**Comment by diegomanuel** [comment]
Thanks @rilax1010 for the response!
