### ISSUE TITLE
Won't update periodically

### ISSUE THREAD

**Issue by suckzkid** [diegomanuel/binance-to-google-sheets#68]
Sometimes the price won't update and shows error as a result of the formula.

**Comment by diegomanuel** [comment]
Expected due to heavy Binance API usage from Google servers.
Latest code on `master` should help but it's not released yet.
Stay tuned, good luck!

**Comment by suckzkid** [comment]
yeah, I hope you'll release it soon mate, and I think you should add a captured value to control the periodical increment and creating a chart to make it easier to read and check. I'm just saying tho, cheers bro!
