### ISSUE TITLE
[BUG] menu buttons is gone, get some error, but it still works somehow

### ISSUE THREAD

**Issue by cristipurdel** [diegomanuel/binance-to-google-sheets#69]
**Describe the bug**
Since last day button menu is gone, gives error below, I guess default settings are used

**To Reproduce**
copy pasted the script, no midifications done

**Expected behavior**
worked fine until yesterday

**Screenshots**
![image](https://user-images.githubusercontent.com/41154308/116825229-9a750c80-ab8e-11eb-9c9b-e7387b979d3e.png)

**Additional context**

**Comment by diegomanuel** [comment]
Seems to be a `=BINANCE()` formula usage with a wrong operation!
It's not and add-on issue/bug, good luck!
