### ISSUE TITLE
[ERROR] The URL has not been whitelisted in the script manifest.

### ISSUE THREAD

**Issue by HexHyte** [diegomanuel/binance-to-google-sheets#82]
**Describe the bug**
Since this morning this message appear on every formula i am using:
"Exception: Request to https://api3.binance.com/api/v3/ticker/price? failed because the URL has not been whitelisted in the script manifest. (row 779)."

**To Reproduce**
=BINANCE("prices","","",TRADES!B1)

**Comment by skalada1** [comment]
The same thing happened to me, but I have solved it by adding in "appscript.json" where "urlFetchWhitelist" the following: 

"urlFetchWhitelist": ["https://api.binance.com/","https://api1.binance.com/","https://api2.binance.com/","https://api3.binance.com/", "https://fapi.binance.com/"]

I hope it works for you

**Comment by HexHyte** [comment]
> The same thing happened to me, but I have solved it by adding in "appscript.json" where "urlFetchWhitelist" the following:
> 
> "urlFetchWhitelist": ["https://api.binance.com/","https://api1.binance.com/","https://api2.binance.com/","https://api3.binance.com/", "https://fapi.binance.com/"]
> 
> I hope it works for you

Yes it worked! Thank you very much ^^

**Comment by brubru13008** [comment]
> 
> 
> The same thing happened to me, but I have solved it by adding in "appscript.json" where "urlFetchWhitelist" the following: 
> 
> 
> 
> "urlFetchWhitelist": ["https://api.binance.com/","https://api1.binance.com/","https://api2.binance.com/","https://api3.binance.com/", "https://fapi.binance.com/"]
> 
> 
> 
> I hope it works for you

Thanks you!!! 
it would be interesting for all users to propose a pull resquest Of this suggestion ? 😉

**Comment by diegomanuel** [comment]
Thanks @skalada1 I've already done the fix but never commit/pushed it, so my bad :sweat_smile: 
@brubru13008 no need to PR, already pushed and updated the latest release's asset file `appsscript.json` manually.
Happy trading, cheers! :beers:
