### ISSUE TITLE
[BUG] Error with URL not in whitelist?

### ISSUE THREAD

**Issue by RogerK888** [diegomanuel/binance-to-google-sheets#83]
Noticed lately that the program is constantly getting an error:

Exception requesting https://api1.binamce.com/account timestamp....  failed because the URL has no been whitelisted in the script manifest.

Is there something we can do our end to stop this problem?

**Comment by RogerK888** [comment]
I worked this out... for anyone having this problem... go to the script editor and add the following to the appscript.json under as:

urlFetchWhitelist": ["https://api1.binance.com/", "https://api2.binance.com/", "https://api3.binance.com/", "https://api4.binance.com/", "https://api.binance.com/", "https://fapi.binance.com/"],

**Comment by diegomanuel** [comment]
Yep, duplicated of #82.
