### ISSUE TITLE
[BUG] Randomly shows "ERROR" without any changes on the table.

### ISSUE THREAD

**Issue by Usr0123** [diegomanuel/binance-to-google-sheets#84]
Hi,

Since 1-2 weeks, ally entries randomly shows this error:

Exception: Request to https://api1.binance.com/api/v3/ticker/price? failed because the URL has not been whitelisted in the script manifest. (line 779).

I didn't change anything in the script or my tables. It still updates prices but only a few times, most of the time the cell would show "ERROR" and need few minutes to show the right price and can come back randomly into "ERROR" the next minute (I have a 1 min update interval).

I'm a bit stuck here,

Thanks for the help and the great tool.

**Comment by diegomanuel** [comment]
Hey @Usr0123 it was resolved at: https://github.com/diegomanuel/binance-to-google-sheets/issues/82
Good luck! :beers:
