### ISSUE TITLE
[FEATURE] Using Websockets.

### ISSUE THREAD

**Issue by claudiazi** [diegomanuel/binance-to-google-sheets#9]
Since I have a bot that trades many coins, I either get a 418 error or an "exceeded maximum execution time" error for the open and done order sheets. This got me to look into the api to see wether I can directly fetch all my trades in one call. Here I stumbled upon the websocket and was thinking that it might actually be more suitable instead of doing many API calls. What are your thoughts?

**Comment by diegomanuel** [comment]
Hey @claudiazi thanks for your question!

It would be great to have websockets support on **Google Apps Script** platform, but sadly it's not supported for now and we entirely rely on Google adding the feature.
Anyways, try the latest version `v0.4.0` that should work WAY better than previous versions and it should help in your case.

Good luck and happy trading, cheers! :beers:
