### ISSUE TITLE
[BUG] Sub-account assets no longer pulled back - error 503

### ISSUE THREAD

**Issue by sophos9** [diegomanuel/binance-to-google-sheets#99]
As of 05:45 UTC+1 today, sub account asset data (free, locked, total etc) is returning a 503 on refresh - check with Binance API team and they report no issues

Adding Sub Account:
1. Try and add sub account in GS Binance > Sub Accounts > Add Sub Account Menu
2. Get "Error: Request failed with status: 503"

BINANCE("account", "sub") function:
1. Add BINANCE("account", "sub") 
2. Get "Error: Request failed with status: 503 (line 831)"

**Expected behavior**
Sub accounts can be added and assets viewed

**Additional context**
Possibly related to removal of "/wapi/v3/sub-account/assets.html" WAPI endpoint

**Comment by sophos9** [comment]
The GS function looks like it can be fixed by changing line 1776 to

     `const data = new BinRequest(opts).get("sapi/v3/sub-account/assets", qs);`

**Comment by sophos9** [comment]
Sub-account menu listing is fixed by changing line 1698 to

`    const data = new BinRequest().get("sapi/v1/sub-account/list");`

**Comment by ddaahk** [comment]
@sophos9 thank you! 🙏

**Comment by diegomanuel** [comment]
Hello there folks, this one was fixed in the latest release: [v0.5.2](https://github.com/diegomanuel/binance-to-google-sheets/releases/tag/v0.5.2)
Cheers! :beers:
